Update 01. Chats.md
glific/docs pull request #91
Opened 2024-02-07 11:54 UTC by SangeetaMishr

Added description on chats and images

2024-02-12 03:58 UTC, mahajantejas reviewed
Hey Sangeeta, 

can you please add the closing tag for the images in this documentation? 

all images should have an ending tag  />

2024-02-13 07:24 UTC, SangeetaMishr commented
@mahajantejas I have added the images and checked in preview it is appearing fine and also added headers and alignment of  text and images, request you to have a final look on it.

2024-02-13 10:10 UTC, mahajantejas requested changes
can you pls add the image url tags

2024-02-13 10:16 UTC, mahajantejas approved these changes

2024-02-13 10:16 UTC, merged